previews:
  generation: automatic
  expireAfterDays: 1

services:
- type: web
  name: jupiter-webui
  runtime: docker
  dockerfilePath: ./src/webui/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  domains:
    - app.get-thriving.com
  previews:
    generation: automatic
    plan: starter
  envVars:
    - key: ENV
      value: production
      previewValue: staging
    - key: HOSTED_GLOBAL_WEBAPI_SERVER_HOST
      fromService:
        name: jupiter-webapi
        type: web
        property: host
    - key: HOSTED_GLOBAL_WEBAPI_SERVER_PORT
      fromService:
        name: jupiter-webapi
        type: web
        property: port
    # - key: DOCS_URL
    #   fromService:
    #     name: jupiter-docs
    #     type: web
    #     property: hostport
- type: web
  name: jupiter-webapi
  runtime: docker
  dockerfilePath: ./src/webapi/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  domains:
    - api.infra.get-thriving.com
  previews:
    generation: automatic
    plan: starter
  disk:
      name: jupiter-data
      mountPath: /data
      sizeGB: 5
  envVars:
    - key: ENV
      value: production
      previewValue: staging
- type: web
  name: jupiter-docs
  runtime: static
  buildCommand: ./scripts/build/docs.sh
  staticPublishPath: .build-cache/docs
  domains:
    - docs.get-thriving.com
  previews:
    generation: automatic
  envVars:
    - key: ENV
      value: production
      previewValue: staging
    - key: POETRY_VERSION
      value: 2.1.1
    - key: PYTHON_VERSION
      value: 3.13.0
