previews:
  generation: automatic
  expireAfterDays: 1

services:
- type: web
  name: jupiter-webui
  runtime: docker
  dockerfilePath: ./src/webui/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  buildFilter:
    paths:
    - gen/**
    - src/webui/**
  previews:
    generation: automatic
    plan: starter
  envVars:
    - key: ENV
      value: production
      previewValue: staging
    - key: HOSTED_GLOBAL_WEBAPI_SERVER_HOST
      fromService:
        name: jupiter-webapi
        type: web
        property: host
    - key: HOSTED_GLOBAL_WEBAPI_SERVER_PORT
      fromService:
        name: jupiter-webapi
        type: web
        property: port
    - key: DOCS_URL
      fromService:
        name: jupiter-docs
        type: web
        property: hostport
- type: web
  name: jupiter-webapi
  runtime: docker
  dockerfilePath: ./src/webapi/Dockerfile
  dockerContext: .
  region: frankfurt
  plan: starter
  autoDeploy: true
  rootDir: .
  numInstances: 1
  healthCheckPath: /healthz
  buildFilter:
    paths:
    - src/core/**
    - src/webapi/**
  previews:
    generation: automatic
    plan: starter
  disk:
      name: jupiter-data
      mountPath: /data
      sizeGB: 5
  envVars:
    - key: ENV
      value: production
      previewValue: staging
- type: web
  name: jupiter-docs
  runtime: static
  buildCommand: ./scripts/build-docs.sh
  staticPublishPath: .build-cache/docs
  previews:
    generation: automatic
  envVars:
    - key: ENV
      value: production
      previewValue: staging
