vars:
  VERSION:
  BUNDLE_ID:
  PUBLIC_NAME:

platforms:
  android:
    versionName: $VERSION
    versionCode: $VERSION
    appName: $PUBLIC_NAME
    packageName: $BUNDLE_ID
  ios:
    targets:
      App:
        version: $VERSION
        buildNumber: $VERSION
        bundleId: $BUNDLE_ID
        displayName: $PUBLIC_NAME
        productName: App
