vars:
  VERSION:
  BUNDLE_ID:
  PUBLIC_NAME:

platforms:
  android:
    versionName: $VERSION
    incrementVersionCode: true
    appName: $PUBLIC_NAME
    packageName: $BUNDLE_ID
  ios:
    targets:
      App:
        version: $VERSION
        incrementBuild: true
        bundleId: $BUNDLE_ID
        displayName: $PUBLIC_NAME
        productName: App
        copy:
        - src: ../../PrivacyInfo.xcprivacy
          dest: PrivacyInfo.xcprivacy
