# Assume Python 3.10
select = ["F", "E", "W", "I", "N", "YTT", "BLE", "B", "A", "DTZ", "T10", "EXE", "ICN", "G", "INP", "PIE", "PYI", "PT", "Q", "RSE", "TID", "PTH", "PLC", "PLE", "RUF"]
extend-exclude = ["migrations"]
target-version = "py310"
line-length = 190  # Black handle this
