name: jupiter

services:
  webapi:
    environment:
      - ENV=production
      - HOSTING=self-hosted
      - PORT=2000
      - AUTH_TOKEN_SECRET=${AUTH_TOKEN_SECRET:?Check https://docs.get-thriving.com/how-tos/self-hosting.html}
    restart: always
    image: horia141/jupiter-webapi:${VERSION:-latest}
    volumes:
      - db:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
  webui:
    environment:
      - ENV=production
      - HOSTING=self-hosted
      - PORT=2000
      - LOCAL_OR_SELF_HOSTED_WEBAPI_SERVER_URL=http://webapi:2000
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-false}
      - SESSION_COOKIE_SECRET=${SESSION_COOKIE_SECRET:?Check https://docs.get-thriving.com/how-tos/self-hosting.html}
    restart: always
    image: horia141/jupiter-webui:${VERSION:-latest}
    depends_on:
      - webapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    image: nginx:1-alpine
    restart: always
    ports:
      - "${PORT:?Check https://docs.get-thriving.com/how-tos/self-hosting.html}:80"
    depends_on:
      - webui
      - webapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./webui.conf:/etc/nginx/conf.d/webui.conf
volumes:
  db:
