---
name: Develop

"on":
  push:
    branches:
      - 'develop'
      - 'feature/**'
      - 'bugfix/**'

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Set up Node 22
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.42.0"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
      - name: Prepare for CI
        run: ./scripts/setup-for-ci.sh
      - name: Check scripts
        run: ./scripts/check/check.sh
